// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by pipeline:
//     terraform
// Using jennies:
//     TerraformDataSourceJenny
//     LatestJenny
//
// Run 'go generate ./' from repository root to regenerate.

package provider

import (
	"context"
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ datasource.DataSource              = &PlaylistDataSource{}
	_ datasource.DataSourceWithConfigure = &PlaylistDataSource{}
)

func NewPlaylistDataSource() datasource.DataSource {
	return &PlaylistDataSource{}
}

// PlaylistDataSource defines the data source implementation.
type PlaylistDataSource struct{}

// PlaylistDataSourceModel describes the data source data model.
type PlaylistDataSourceModel struct {
	Uid      types.String `tfsdk:"uid" json:"uid"`
	Name     types.String `tfsdk:"name" json:"name"`
	Interval types.String `tfsdk:"interval" json:"interval"`
	Items    []struct {
		Type  types.String `tfsdk:"type" json:"type"`
		Value types.String `tfsdk:"value" json:"value"`
		Title types.String `tfsdk:"title" json:"title"`
	} `tfsdk:"items" json:"items"`
	ToJSON types.String `tfsdk:"to_json"`
}

func (d *PlaylistDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_playlist"
}

func (d *PlaylistDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "TODO description",

		Attributes: map[string]schema.Attribute{
			"uid": schema.StringAttribute{
				MarkdownDescription: `Unique playlist identifier. Generated on creation, either by the
creator of the playlist of by the application.`,
				Computed: false,
				Optional: false,
				Required: true,
			},

			"name": schema.StringAttribute{
				MarkdownDescription: `Name of the playlist.`,
				Computed:            false,
				Optional:            false,
				Required:            true,
			},

			"interval": schema.StringAttribute{
				MarkdownDescription: `Interval sets the time between switching views in a playlist.
FIXME: Is this based on a standardized format or what options are available? Can datemath be used?`,
				Computed: false,
				Optional: false,
				Required: true,
			},

			"items": schema.ListNestedAttribute{
				MarkdownDescription: `The ordered list of items that the playlist will iterate over.
FIXME! This should not be optional, but changing it makes the godegen awkward`,
				Computed: false,
				Optional: true,
				Required: false,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"type": schema.StringAttribute{
							MarkdownDescription: `Type of the item.`,
							Computed:            false,
							Optional:            false,
							Required:            true,
						},

						"value": schema.StringAttribute{
							MarkdownDescription: `Value depends on type and describes the playlist item.

 - dashboard_by_id: The value is an internal numerical identifier set by Grafana. This
 is not portable as the numerical identifier is non-deterministic between different instances.
 Will be replaced by dashboard_by_uid in the future. (deprecated)
 - dashboard_by_tag: The value is a tag which is set on any number of dashboards. All
 dashboards behind the tag will be added to the playlist.
 - dashboard_by_uid: The value is the dashboard UID`,
							Computed: false,
							Optional: false,
							Required: true,
						},

						"title": schema.StringAttribute{
							MarkdownDescription: `Title is an unused property -- it will be removed in the future`,
							Computed:            false,
							Optional:            true,
							Required:            false,
						},
					},
				},
			},

			"to_json": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "This datasource rendered as JSON",
			},
		},
	}
}

func (d *PlaylistDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
}

func (d *PlaylistDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data PlaylistDataSourceModel

	// Read Terraform configuration data into the model
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	JSONConfig, err := json.Marshal(data)
	if err != nil {
		resp.Diagnostics.AddError("JSON marshalling error", err.Error())
		return
	}

	// Not sure about that
	data.ToJSON = types.StringValue(string(JSONConfig))

	// Write logs using the tflog package
	// Documentation: https://terraform.io/plugin/log
	tflog.Trace(ctx, "read a data source")

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
